from __future__ import annotations

from .activity_math import (
    _author_color,
    _author_configured_time_zone_id,
    _author_has_summary_activity,
    _author_time_zone_id,
    _cached_author_avatar_api_url,
    _clear_inactive_author_report_metadata,
    _display_name,
    _github_login_from_profile_doc,
    _github_username_for_avatar_fetch,
    _github_username_ui_default,
    _normalize_author,
    _normalize_discord_user_id,
    _normalize_email,
    _normalize_github_username,
    _normalize_telegram_username,
    _public_site_user,
    _should_track_plugin_staleness,
    _valid_color,
    _with_activity_mix,
    _with_author_presence,
    _with_productivity,
)

__all__ = [
    "_author_color",
    "_author_configured_time_zone_id",
    "_author_has_summary_activity",
    "_author_time_zone_id",
    "_cached_author_avatar_api_url",
    "_clear_inactive_author_report_metadata",
    "_display_name",
    "_github_login_from_profile_doc",
    "_github_username_for_avatar_fetch",
    "_github_username_ui_default",
    "_normalize_author",
    "_normalize_discord_user_id",
    "_normalize_email",
    "_normalize_github_username",
    "_normalize_telegram_username",
    "_public_site_user",
    "_should_track_plugin_staleness",
    "_valid_color",
    "_with_activity_mix",
    "_with_author_presence",
    "_with_productivity",
]
